const { PrismaClient } = require("@prisma/client");
const bcrypt = require("bcrypt");

const prisma = new PrismaClient();

const avatarUrl = "https://cyber.comolho.com/static/img/avatar.png";

const seedUsers = [
  {
    name: "Aarav Sharma",
    email: "aarav@gamil.com",
    password: "Aarav@123",
    age: 22,
    bio: "Machine learning enthusiast focused on predictive modeling, feature engineering, and applied AI systems.",
    skills: ["Python", "Scikit-learn", "Pandas", "NumPy", "Model Evaluation"],
    location: "Bengaluru, India",
    role: "Machine Learning Engineer",
  },
  {
    name: "Ishita Verma",
    email: "ishita@gamil.com",
    password: "Ishita@123",
    age: 21,
    bio: "Computer science student with strong foundations in algorithms, problem solving, and software development.",
    skills: ["C++", "Java", "Data Structures", "Algorithms", "Problem Solving"],
    location: "Delhi, India",
    role: "Computer Science Student",
  },
  {
    name: "Rohan Mehta",
    email: "rohan@gamil.com",
    password: "Rohan@123",
    age: 23,
    bio: "Deep learning practitioner working on neural networks, image models, and scalable ML experimentation.",
    skills: ["Python", "TensorFlow", "Keras", "Neural Networks", "Deep Learning"],
    location: "Mumbai, India",
    role: "Deep Learning Engineer",
  },
  {
    name: "Sneha Patel",
    email: "sneha@gamil.com",
    password: "Sneha@123",
    age: 22,
    bio: "Backend and database-focused developer interested in designing efficient and scalable systems.",
    skills: ["SQL", "MongoDB", "Database Design", "Node.js", "Express"],
    location: "Ahmedabad, India",
    role: "Backend Developer",
  },
  {
    name: "Vivaan Kapoor",
    email: "vivaan@gamil.com",
    password: "Vivaan@123",
    age: 24,
    bio: "NLP-focused builder interested in transformers, language understanding, and conversational AI applications.",
    skills: ["Python", "NLP", "Transformers", "PyTorch", "Text Processing"],
    location: "Pune, India",
    role: "NLP Engineer",
  },
  {
    name: "Ananya Reddy",
    email: "ananya@gamil.com",
    password: "Ananya@123",
    age: 21,
    bio: "Systems-oriented computer science learner exploring operating systems, concurrency, and low-level programming.",
    skills: ["C", "Linux", "Operating Systems", "Concurrency", "System Programming"],
    location: "Hyderabad, India",
    role: "Systems Programmer",
  },
  {
    name: "Aditya Nair",
    email: "aditya@gamil.com",
    password: "Aditya@123",
    age: 23,
    bio: "Computer vision enthusiast building models for image understanding, recognition, and visual intelligence.",
    skills: ["OpenCV", "PyTorch", "CNN", "Image Processing", "Computer Vision"],
    location: "Kochi, India",
    role: "Computer Vision Engineer",
  },
  {
    name: "Kavya Iyer",
    email: "kavya@gamil.com",
    password: "Kavya@123",
    age: 22,
    bio: "Full-stack developer with a strong interest in modern web platforms and scalable application design.",
    skills: ["JavaScript", "React", "Node.js", "Express", "REST APIs"],
    location: "Chennai, India",
    role: "Full Stack Developer",
  },
  {
    name: "Arjun Malhotra",
    email: "arjun@gamil.com",
    password: "Arjun@123",
    age: 24,
    bio: "AI enthusiast exploring reinforcement learning, intelligent agents, and decision-making systems.",
    skills: ["Python", "Reinforcement Learning", "PyTorch", "OpenAI Gym", "Decision Systems"],
    location: "Noida, India",
    role: "AI Research Student",
  },
  {
    name: "Meera Joshi",
    email: "meera@gamil.com",
    password: "Meera@123",
    age: 22,
    bio: "Cybersecurity-focused computer science learner interested in secure systems, networks, and cryptography.",
    skills: ["Network Security", "Cryptography", "Python", "Ethical Hacking", "Security Analysis"],
    location: "Jaipur, India",
    role: "Cybersecurity Analyst",
  },
  {
    name: "Devansh Gupta",
    email: "devansh@gamil.com",
    password: "Devansh@123",
    age: 23,
    bio: "Software engineer interested in distributed systems, backend APIs, and scalable service design.",
    skills: ["Node.js", "Distributed Systems", "MongoDB", "REST APIs", "System Design"],
    location: "Gurugram, India",
    role: "Software Engineer",
  },
  {
    name: "Priya Nanda",
    email: "priya@gamil.com",
    password: "Priya@123",
    age: 22,
    bio: "Data science learner building models for classification, forecasting, and practical analytics.",
    skills: ["Python", "Data Analysis", "Pandas", "Machine Learning", "Visualization"],
    location: "Bhubaneswar, India",
    role: "Data Scientist",
  },
  {
    name: "Rahul Sethi",
    email: "rahul@gamil.com",
    password: "Rahul@123",
    age: 24,
    bio: "Cloud-focused developer working on containerized services and deployment automation.",
    skills: ["Docker", "AWS", "CI/CD", "Linux", "Node.js"],
    location: "Chandigarh, India",
    role: "Cloud Engineer",
  },
  {
    name: "Nikita Rao",
    email: "nikita@gamil.com",
    password: "Nikita@123",
    age: 21,
    bio: "Frontend engineer who enjoys building responsive interfaces and accessible web experiences.",
    skills: ["React", "JavaScript", "CSS", "Accessibility", "UI Development"],
    location: "Mysuru, India",
    role: "Frontend Developer",
  },
  {
    name: "Samar Bhatia",
    email: "samar@gamil.com",
    password: "Samar@123",
    age: 23,
    bio: "ML engineer exploring recommendation systems, ranking models, and feature pipelines.",
    skills: ["Python", "Recommendation Systems", "Feature Engineering", "SQL", "XGBoost"],
    location: "Lucknow, India",
    role: "ML Engineer",
  },
  {
    name: "Tanya Arora",
    email: "tanya@gamil.com",
    password: "Tanya@123",
    age: 22,
    bio: "Computer science graduate interested in secure coding, web security, and threat mitigation.",
    skills: ["OWASP", "Python", "Web Security", "Security Testing", "Networking"],
    location: "Amritsar, India",
    role: "Security Engineer",
  },
  {
    name: "Karan Bedi",
    email: "karan@gamil.com",
    password: "Karan@123",
    age: 24,
    bio: "Backend engineer building robust APIs and efficient data access layers for modern applications.",
    skills: ["Express", "PostgreSQL", "API Design", "Caching", "TypeScript"],
    location: "Faridabad, India",
    role: "Backend Engineer",
  },
  {
    name: "Ritika Sen",
    email: "ritika@gamil.com",
    password: "Ritika@123",
    age: 21,
    bio: "AI student working on NLP systems, text embeddings, and retrieval-based applications.",
    skills: ["NLP", "Embeddings", "PyTorch", "Transformers", "Vector Search"],
    location: "Kolkata, India",
    role: "AI Student",
  },
  {
    name: "Yash Thakur",
    email: "yash@gamil.com",
    password: "Yash@123",
    age: 23,
    bio: "Systems engineer interested in networking, operating systems, and performance optimization.",
    skills: ["Linux", "Networking", "C", "Performance Tuning", "Shell Scripting"],
    location: "Nagpur, India",
    role: "Systems Engineer",
  },
  {
    name: "Pooja Kulkarni",
    email: "pooja@gamil.com",
    password: "Pooja@123",
    age: 22,
    bio: "Full-stack developer focused on product features, clean APIs, and practical user experiences.",
    skills: ["React", "Node.js", "MongoDB", "Express", "Product Development"],
    location: "Nashik, India",
    role: "Full Stack Engineer",
  },
  {
    name: "Harshit Jain",
    email: "harshit@gamil.com",
    password: "Harshit@123",
    age: 24,
    bio: "ML practitioner building models for computer vision, object detection, and video understanding.",
    skills: ["Computer Vision", "OpenCV", "PyTorch", "Object Detection", "Deep Learning"],
    location: "Indore, India",
    role: "Computer Vision Researcher",
  },
  {
    name: "Aditi Kapoor",
    email: "aditi@gamil.com",
    password: "Aditi@123",
    age: 21,
    bio: "Aspiring software developer with strong algorithmic thinking and interest in coding platforms.",
    skills: ["Java", "DSA", "Problem Solving", "OOP", "Competitive Programming"],
    location: "Patiala, India",
    role: "Software Developer",
  },
  {
    name: "Mohit Suri",
    email: "mohit@gamil.com",
    password: "Mohit@123",
    age: 23,
    bio: "Data engineer focused on pipelines, ETL workflows, and reliable batch processing systems.",
    skills: ["Python", "ETL", "SQL", "Airflow", "Data Pipelines"],
    location: "Surat, India",
    role: "Data Engineer",
  },
  {
    name: "Neha Chawla",
    email: "neha@gamil.com",
    password: "Neha@123",
    age: 22,
    bio: "Developer interested in web application architecture, frontend systems, and design consistency.",
    skills: ["React", "Design Systems", "JavaScript", "CSS", "Frontend Architecture"],
    location: "Dehradun, India",
    role: "UI Engineer",
  },
  {
    name: "Laksh Verma",
    email: "laksh@gamil.com",
    password: "Laksh@123",
    age: 24,
    bio: "Engineer exploring reinforcement learning, simulation, and decision-making algorithms.",
    skills: ["Reinforcement Learning", "Python", "Gymnasium", "PyTorch", "Simulation"],
    location: "Kanpur, India",
    role: "RL Engineer",
  },
  {
    name: "Simran Kaur",
    email: "simran@gamil.com",
    password: "Simran@123",
    age: 22,
    bio: "Cybersecurity learner focused on network defense, monitoring, and secure infrastructure basics.",
    skills: ["Cybersecurity", "Network Defense", "SIEM", "Python", "Incident Analysis"],
    location: "Ludhiana, India",
    role: "Security Analyst",
  },
  {
    name: "Varun Pillai",
    email: "varun@gamil.com",
    password: "Varun@123",
    age: 23,
    bio: "Backend and infra-focused developer building resilient services and asynchronous processing workflows.",
    skills: ["Node.js", "Queues", "Redis", "API Development", "Observability"],
    location: "Thiruvananthapuram, India",
    role: "Platform Engineer",
  },
  {
    name: "Diya Menon",
    email: "diya@gamil.com",
    password: "Diya@123",
    age: 21,
    bio: "AI enthusiast interested in LLM applications, prompt workflows, and educational tools.",
    skills: ["Python", "LLM Apps", "Prompting", "NLP", "APIs"],
    location: "Kozhikode, India",
    role: "AI Application Developer",
  },
  {
    name: "Manav Sood",
    email: "manav@gamil.com",
    password: "Manav@123",
    age: 24,
    bio: "Cloud-native engineer working on deployment automation, monitoring, and scalable runtime systems.",
    skills: ["Kubernetes", "Docker", "Prometheus", "AWS", "Terraform"],
    location: "Shimla, India",
    role: "DevOps Engineer",
  },
  {
    name: "Shruti Bansal",
    email: "shruti@gamil.com",
    password: "Shruti@123",
    age: 22,
    bio: "Data analyst with strong interest in dashboards, business intelligence, and ML-assisted insights.",
    skills: ["SQL", "Power BI", "Python", "Statistics", "Data Visualization"],
    location: "Meerut, India",
    role: "Data Analyst",
  },
  {
    name: "Ujjwal Roy",
    email: "ujjwal@gamil.com",
    password: "Ujjwal@123",
    age: 23,
    bio: "Engineer interested in search systems, ranking pipelines, and information retrieval.",
    skills: ["Search", "Elasticsearch", "Ranking", "Python", "Information Retrieval"],
    location: "Ranchi, India",
    role: "Search Engineer",
  },
  {
    name: "Palak Sinha",
    email: "palak@gamil.com",
    password: "Palak@123",
    age: 21,
    bio: "Student building projects in app development, web APIs, and practical software engineering.",
    skills: ["JavaScript", "Node.js", "MongoDB", "Git", "REST APIs"],
    location: "Patna, India",
    role: "CS Student",
  },
  {
    name: "Abhinav Rawat",
    email: "abhinav@gamil.com",
    password: "Abhinav@123",
    age: 24,
    bio: "Machine learning engineer working on tabular models, feature stores, and model deployment.",
    skills: ["Python", "ML Ops", "Feature Stores", "FastAPI", "Model Serving"],
    location: "Bhopal, India",
    role: "ML Ops Engineer",
  },
  {
    name: "Ira Dutta",
    email: "ira@gamil.com",
    password: "Ira@123",
    age: 22,
    bio: "Frontend-focused developer interested in performance, interaction design, and polished product UX.",
    skills: ["React", "Performance Optimization", "CSS", "Animations", "UI Engineering"],
    location: "Guwahati, India",
    role: "Frontend Engineer",
  },
  {
    name: "Kabir Anand",
    email: "kabir@gamil.com",
    password: "Kabir@123",
    age: 23,
    bio: "Software engineer building backend services, auth flows, and production-ready APIs.",
    skills: ["Node.js", "Authentication", "MongoDB", "Express", "API Security"],
    location: "Jalandhar, India",
    role: "API Engineer",
  },
  {
    name: "Suhani Desai",
    email: "suhani@gamil.com",
    password: "Suhani@123",
    age: 21,
    bio: "Student researcher exploring natural language processing and practical deep learning workflows.",
    skills: ["PyTorch", "Transformers", "NLP", "Research", "Python"],
    location: "Vadodara, India",
    role: "NLP Research Student",
  },
  {
    name: "Rudra Bose",
    email: "rudra@gamil.com",
    password: "Rudra@123",
    age: 24,
    bio: "Engineer focused on secure backend services, rate limiting, and resilient application design.",
    skills: ["Express", "Security", "Rate Limiting", "Redis", "Node.js"],
    location: "Siliguri, India",
    role: "Backend Security Engineer",
  },
  {
    name: "Khushi Yadav",
    email: "khushi@gamil.com",
    password: "Khushi@123",
    age: 22,
    bio: "Developer interested in recommendation engines, personalization, and user behavior analytics.",
    skills: ["Python", "Personalization", "Recommendation Systems", "Analytics", "SQL"],
    location: "Prayagraj, India",
    role: "Recommendation Engineer",
  },
  {
    name: "Aryan Chatterjee",
    email: "aryan@gamil.com",
    password: "Aryan@123",
    age: 23,
    bio: "Cloud engineer building automated infrastructure, secure deployments, and platform tooling.",
    skills: ["AWS", "Terraform", "CI/CD", "Linux", "Infrastructure Automation"],
    location: "Durgapur, India",
    role: "Infrastructure Engineer",
  },
  {
    name: "Niharika Paul",
    email: "niharika@gamil.com",
    password: "Niharika@123",
    age: 21,
    bio: "Computer science student interested in backend systems, software testing, and clean code practices.",
    skills: ["Java", "Testing", "Spring Basics", "Git", "OOP"],
    location: "Agartala, India",
    role: "Software Engineering Student",
  },
  {
    name: "Parth Tiwari",
    email: "parth@gamil.com",
    password: "Parth@123",
    age: 24,
    bio: "Engineer exploring graph algorithms, data structures, and advanced problem solving.",
    skills: ["C++", "Graphs", "Algorithms", "Competitive Programming", "Data Structures"],
    location: "Varanasi, India",
    role: "Algorithm Engineer",
  },
  {
    name: "Rhea Malhotra",
    email: "rhea@gamil.com",
    password: "Rhea@123",
    age: 23,
    bio: "Finance-focused analyst interested in valuation, financial modeling, and market research.",
    skills: ["Financial Modeling", "Excel", "Equity Research", "Valuation", "Market Analysis"],
    location: "Mumbai, India",
    role: "Finance Analyst",
  },
  {
    name: "Ayaan Khanna",
    email: "ayaan@gamil.com",
    password: "Ayaan@123",
    age: 24,
    bio: "Entrepreneur building digital products with a focus on early-stage growth and customer discovery.",
    skills: ["Startup Strategy", "Growth", "Product Validation", "Pitching", "Sales"],
    location: "Bengaluru, India",
    role: "Entrepreneur",
  },
  {
    name: "Mira Fernandes",
    email: "mira@gamil.com",
    password: "Mira@123",
    age: 22,
    bio: "Designer creating thoughtful interfaces and brand experiences for digital products.",
    skills: ["UI Design", "Figma", "Branding", "Typography", "Design Systems"],
    location: "Goa, India",
    role: "Product Designer",
  },
  {
    name: "Rishabh Bansal",
    email: "rishabh@gamil.com",
    password: "Rishabh@123",
    age: 23,
    bio: "Finance learner working on investment analysis, budgeting, and financial planning.",
    skills: ["Accounting", "Budgeting", "Financial Analysis", "Excel", "Forecasting"],
    location: "Delhi, India",
    role: "Financial Planning Analyst",
  },
  {
    name: "Kiara Sethi",
    email: "kiara@gamil.com",
    password: "Kiara@123",
    age: 22,
    bio: "Startup-minded builder interested in launching creator tools and community-led products.",
    skills: ["Founder Mindset", "Community Growth", "Market Research", "Product Strategy", "Operations"],
    location: "Pune, India",
    role: "Startup Founder",
  },
  {
    name: "Aria Kapoor",
    email: "aria@gamil.com",
    password: "Aria@123",
    age: 21,
    bio: "Visual designer focused on interface polish, layout systems, and clean digital branding.",
    skills: ["Visual Design", "Figma", "Wireframing", "Color Systems", "Brand Identity"],
    location: "Jaipur, India",
    role: "Visual Designer",
  },
  {
    name: "Tanmay Luthra",
    email: "tanmay@gamil.com",
    password: "Tanmay@123",
    age: 24,
    bio: "Finance professional interested in risk analysis, investments, and portfolio management.",
    skills: ["Risk Analysis", "Portfolio Management", "Financial Markets", "Excel", "Reporting"],
    location: "Gurugram, India",
    role: "Investment Analyst",
  },
  {
    name: "Sana Merchant",
    email: "sana@gamil.com",
    password: "Sana@123",
    age: 23,
    bio: "Entrepreneurial operator who enjoys launching services, validating ideas, and building partnerships.",
    skills: ["Business Development", "Partnerships", "Customer Discovery", "Pitch Decks", "Operations"],
    location: "Ahmedabad, India",
    role: "Business Founder",
  },
  {
    name: "Zoya Chhabra",
    email: "zoya@gamil.com",
    password: "Zoya@123",
    age: 22,
    bio: "UX designer passionate about research-driven interfaces and intuitive product journeys.",
    skills: ["UX Research", "User Flows", "Prototyping", "Figma", "Interaction Design"],
    location: "Chandigarh, India",
    role: "UX Designer",
  },
  {
    name: "Dhruv Anand",
    email: "dhruv@gamil.com",
    password: "Dhruv@123",
    age: 24,
    bio: "Finance enthusiast working on corporate finance concepts, metrics, and business performance.",
    skills: ["Corporate Finance", "Financial Statements", "Forecasting", "Excel", "KPIs"],
    location: "Noida, India",
    role: "Corporate Finance Associate",
  },
  {
    name: "Ishaan Grover",
    email: "ishaan@gamil.com",
    password: "Ishaan@123",
    age: 23,
    bio: "Founder-in-progress exploring SaaS products, GTM strategy, and startup execution.",
    skills: ["Go-to-Market", "Startup Execution", "Product Thinking", "Sales", "User Interviews"],
    location: "Hyderabad, India",
    role: "SaaS Entrepreneur",
  },
  {
    name: "Tara Dsouza",
    email: "tara@gamil.com",
    password: "Tara@123",
    age: 21,
    bio: "Creative designer working across mobile interfaces, branding, and modern visual systems.",
    skills: ["Mobile UI", "Brand Design", "Typography", "Figma", "Illustration"],
    location: "Mangaluru, India",
    role: "UI Designer",
  },
  {
    name: "Kushagra Mittal",
    email: "kushagra@gamil.com",
    password: "Kushagra@123",
    age: 24,
    bio: "Finance-oriented professional interested in business analysis, cash flow planning, and reporting.",
    skills: ["Cash Flow Analysis", "Financial Reporting", "Excel", "Business Metrics", "Planning"],
    location: "Kanpur, India",
    role: "Business Finance Analyst",
  },
  {
    name: "Anika Talwar",
    email: "anika@gamil.com",
    password: "Anika@123",
    age: 22,
    bio: "Entrepreneur passionate about consumer brands, storytelling, and early growth experiments.",
    skills: ["Brand Strategy", "Growth Experiments", "Consumer Insights", "Marketing", "Operations"],
    location: "Ludhiana, India",
    role: "Brand Entrepreneur",
  },
  {
    name: "Yana Pillai",
    email: "yana@gamil.com",
    password: "Yana@123",
    age: 23,
    bio: "Design systems specialist focused on consistency, accessibility, and scalable UI patterns.",
    skills: ["Design Systems", "Accessibility", "Component Libraries", "Figma", "UI Audits"],
    location: "Kochi, India",
    role: "Design Systems Designer",
  },
  {
    name: "Ritvik Saran",
    email: "ritvik@gamil.com",
    password: "Ritvik@123",
    age: 24,
    bio: "Aspiring finance professional interested in fintech, credit analysis, and market trends.",
    skills: ["Fintech", "Credit Analysis", "Excel", "Research", "Financial Ratios"],
    location: "Indore, India",
    role: "Fintech Analyst",
  },
  {
    name: "Nysa Arora",
    email: "nysa@gamil.com",
    password: "Nysa@123",
    age: 22,
    bio: "Startup enthusiast building communities and testing ideas around creator-led products.",
    skills: ["Community Building", "Growth Loops", "Creator Economy", "User Research", "Content Strategy"],
    location: "Dehradun, India",
    role: "Community Entrepreneur",
  },
  {
    name: "Viaan Basu",
    email: "viaan@gamil.com",
    password: "Viaan@123",
    age: 21,
    bio: "Graphic and digital designer interested in brand identity, layout systems, and campaign assets.",
    skills: ["Graphic Design", "Brand Assets", "Adobe XD", "Layout", "Visual Storytelling"],
    location: "Kolkata, India",
    role: "Graphic Designer",
  },
  {
    name: "Pranav Walia",
    email: "pranavw@gamil.com",
    password: "Pranavw@123",
    age: 24,
    bio: "Finance graduate focused on auditing basics, compliance awareness, and structured reporting.",
    skills: ["Auditing", "Compliance", "Financial Reporting", "Excel", "Documentation"],
    location: "Bhopal, India",
    role: "Audit Associate",
  },
  {
    name: "Myra Shetty",
    email: "myra@gamil.com",
    password: "Myra@123",
    age: 23,
    bio: "Entrepreneur with an interest in product-led growth, startup experiments, and digital services.",
    skills: ["Product-Led Growth", "MVPs", "Startup Ops", "User Feedback", "Product Strategy"],
    location: "Mysuru, India",
    role: "Product Entrepreneur",
  },
  {
    name: "Esha Nair",
    email: "esha@gamil.com",
    password: "Esha@123",
    age: 22,
    bio: "Interaction designer crafting clean workflows, responsive experiences, and micro-interactions.",
    skills: ["Interaction Design", "Prototyping", "Figma", "Usability", "Responsive Design"],
    location: "Thiruvananthapuram, India",
    role: "Interaction Designer",
  },
  {
    name: "Arnav Oberoi",
    email: "arnav@gamil.com",
    password: "Arnav@123",
    age: 24,
    bio: "Finance and business enthusiast interested in startup finance, runway planning, and capital efficiency.",
    skills: ["Startup Finance", "Runway Planning", "Financial Models", "Excel", "Metrics"],
    location: "Chennai, India",
    role: "Startup Finance Associate",
  },
  {
    name: "Kashvi Rao",
    email: "kashvi@gamil.com",
    password: "Kashvi@123",
    age: 21,
    bio: "Builder interested in social ventures, venture ideation, and practical business experimentation.",
    skills: ["Venture Building", "Ideation", "Field Research", "Pitching", "Operations"],
    location: "Patna, India",
    role: "Social Entrepreneur",
  },
  {
    name: "Reyansh Sikka",
    email: "reyansh@gamil.com",
    password: "Reyansh@123",
    age: 23,
    bio: "Brand and product designer focused on digital identity, user journeys, and polished presentations.",
    skills: ["Brand Systems", "UX Writing", "Presentations", "Figma", "Product Mockups"],
    location: "Surat, India",
    role: "Brand Designer",
  },
  {
    name: "Lavanya Bose",
    email: "lavanya@gamil.com",
    password: "Lavanya@123",
    age: 22,
    bio: "Finance student interested in taxation basics, accounting workflows, and personal finance education.",
    skills: ["Tax Basics", "Accounting", "Excel", "Personal Finance", "Documentation"],
    location: "Nagpur, India",
    role: "Finance Student",
  },
  {
    name: "Devika Menon",
    email: "devika@gamil.com",
    password: "Devika@123",
    age: 23,
    bio: "Entrepreneurial builder working on creator tools, monetization experiments, and business growth.",
    skills: ["Monetization", "Creator Tools", "Business Growth", "User Research", "Launch Strategy"],
    location: "Kozhikode, India",
    role: "Digital Entrepreneur",
  },
  {
    name: "Aarohi Paul",
    email: "aarohi@gamil.com",
    password: "Aarohi@123",
    age: 21,
    bio: "Designer interested in product visuals, mobile-first experiences, and elegant interface systems.",
    skills: ["Product Visuals", "Mobile Design", "Figma", "Layout", "Design Critique"],
    location: "Guwahati, India",
    role: "Mobile Product Designer",
  },
  {
    name: "Harshvardhan Rao",
    email: "harshvardhan@gamil.com",
    password: "Harshvardhan@123",
    age: 24,
    bio: "Finance professional focused on business health metrics, investment thinking, and strategic planning.",
    skills: ["Business Metrics", "Investment Thinking", "Strategic Planning", "Excel", "Analysis"],
    location: "Vadodara, India",
    role: "Strategic Finance Analyst",
  },
  {
    name: "Samaira Khurana",
    email: "samaira@gamil.com",
    password: "Samaira@123",
    age: 22,
    bio: "Entrepreneur exploring D2C ideas, customer behavior, and growth through experimentation.",
    skills: ["D2C", "Consumer Research", "Growth", "Campaign Planning", "Founder Ops"],
    location: "Jalandhar, India",
    role: "D2C Entrepreneur",
  },
  {
    name: "Neil Joseph",
    email: "neil@gamil.com",
    password: "Neil@123",
    age: 23,
    bio: "Designer focused on user-centered product thinking, interface systems, and prototype communication.",
    skills: ["User-Centered Design", "Prototypes", "Figma", "UI Reviews", "Design Communication"],
    location: "Goa, India",
    role: "UX/UI Designer",
  },
];

const toExpertise = (user) => ({
  name: user.name,
  description: user.bio,
  experience: "Student and project-based experience in computer science and applied machine learning.",
  skills: user.skills,
  projects: `${user.role} portfolio covering practical projects in ${user.skills.slice(0, 3).join(", ")}.`,
  achievements: `Built academic and personal projects related to ${user.role.toLowerCase()}.`,
  interests: user.location,
  aboutYou: user.bio,
  details: {
    email: user.email,
    address: user.location,
  },
  format: 1,
});

async function main() {
  for (const user of seedUsers) {
    const [firstname, ...lastnameParts] = user.name.split(" ");
    const lastname = lastnameParts.join(" ") || "User";
    const passwordHash = await bcrypt.hash(user.password, 10);

    await prisma.users.upsert({
      where: { email: user.email },
      update: {
        firstname,
        lastname,
        age: user.age,
        password: passwordHash,
        authProvider: "local",
        role: "user",
        isBlocked: false,
        imageUrl: avatarUrl,
        expertise: toExpertise(user),
      },
      create: {
        firstname,
        lastname,
        email: user.email,
        age: user.age,
        password: passwordHash,
        authProvider: "local",
        role: "user",
        isBlocked: false,
        imageUrl: avatarUrl,
        expertise: toExpertise(user),
        conversationsIds: [],
      },
    });
  }

  console.log(`Seeded ${seedUsers.length} users successfully.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
